/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef slave_controller_TYPES_H
#define slave_controller_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace slave_controller {

struct ScannerStatus {
  enum type {
    Ready = 1,
    Stop = 2
  };
};

extern const std::map<int, const char*> _ScannerStatus_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ScannerStatus::type& val);

std::string to_string(const ScannerStatus::type& val);

} // namespace

#endif
